#!/usr/bin/env bash

curl -o install-openshift.sh https://raw.githubusercontent.com/cmcornejocrespo/installcentos/master/install-openshift.sh
chmod +x install-openshift.sh
./install-openshift.sh
echo "Don't forget to add console.$DOMAIN to your /etc/hosts"